name: CI
on: [push, pull_request]
jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - "3.0"
          - "3.1"
          - "3.2"
          - "3.3"
        gemfile:
          - Gemfile
          - gemfiles/rails_7_0_propshaft.gemfile
          - gemfiles/rails_7_1_propshaft.gemfile
          - gemfiles/rails_main_propshaft.gemfile
          - gemfiles/rails_7_0_sprockets.gemfile
          - gemfiles/rails_7_1_sprockets.gemfile
          - gemfiles/rails_main_sprockets.gemfile
        exclude:
          - ruby-version: "3.0"
            gemfile: gemfiles/rails_main_propshaft.gemfile
          - ruby-version: "3.0"
            gemfile: gemfiles/rails_main_sprockets.gemfile
        continue-on-error: [ false ]

    name: ${{ format('Tests (Ruby {0}, {1})', matrix.ruby-version, matrix.gemfile) }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.continue-on-error }}

    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}

    steps:
      - uses: actions/checkout@v4

      - name: Remove Gemfile lock
        run: |
          rm -f $BUNDLE_GEMFILE.lock

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      # This prevents a "Failed to build gem native extension" error when
      # running `bundle install` inside a Rails app that is generated for
      # testing. The error occurs only in CI, and only when using Ruby 3.0 and
      # Rails >= 7.1.
      - name: Install sass-embedded gem
        if: ${{ matrix.ruby-version == '3.0' }}
        run: gem install sass-embedded

      - name: Run tests
        run: |
          bundle exec rake
