name: CI
on: [push, pull_request]
jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - "3.1"
          - "3.2"
          - "3.3"
          - "3.4"
        gemfile:
          - gemfiles/rails_6_1.gemfile
          - gemfiles/rails_7_0.gemfile
          - gemfiles/rails_7_1.gemfile
          - gemfiles/rails_7_2.gemfile
          - gemfiles/rails_8_0.gemfile
          - gemfiles/rails_main.gemfile
        continue-on-error: [ false ]
        exclude:
          - ruby-version: "3.3"
            gemfile: gemfiles/rails_6_1.gemfile
          - ruby-version: "3.4"
            gemfile: gemfiles/rails_6_1.gemfile
          - ruby-version: "3.4"
            gemfile: gemfiles/rails_7_0.gemfile
          - ruby-version: "3.1"
            gemfile: gemfiles/rails_8_0.gemfile
          - ruby-version: "3.1"
            gemfile: gemfiles/rails_main.gemfile

    name: ${{ format('Tests (Ruby {0}, {1})', matrix.ruby-version, matrix.gemfile) }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.continue-on-error }}

    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}

    steps:
      - uses: actions/checkout@v4

      - name: Remove Gemfile lock
        run: |
          rm -f $BUNDLE_GEMFILE.lock

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run tests
        run: |
          bundle exec rake
